# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/addBook.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(672, 501)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/resources/icons/description_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(26,26,26);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Login_9 = QtWidgets.QLabel(self.centralwidget)
        self.Login_9.setEnabled(False)
        self.Login_9.setGeometry(QtCore.QRect(99, 380, 131, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Login_9.sizePolicy().hasHeightForWidth())
        self.Login_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Login_9.setFont(font)
        self.Login_9.setStyleSheet("color: rgb(166, 166, 166);\n"
"background-color: rgb(26,26,26);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;")
        self.Login_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Login_9.setObjectName("Login_9")
        self.Login_4 = QtWidgets.QLabel(self.centralwidget)
        self.Login_4.setEnabled(False)
        self.Login_4.setGeometry(QtCore.QRect(0, 90, 231, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Login_4.sizePolicy().hasHeightForWidth())
        self.Login_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Login_4.setFont(font)
        self.Login_4.setStyleSheet("color: rgb(166, 166, 166);\n"
"background-color: rgb(26,26,26);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;")
        self.Login_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Login_4.setObjectName("Login_4")
        self.Login_3 = QtWidgets.QLabel(self.centralwidget)
        self.Login_3.setEnabled(False)
        self.Login_3.setGeometry(QtCore.QRect(131, 60, 101, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Login_3.sizePolicy().hasHeightForWidth())
        self.Login_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Login_3.setFont(font)
        self.Login_3.setStyleSheet("color: rgb(166, 166, 166);\n"
"background-color: rgb(26,26,26);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;")
        self.Login_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Login_3.setObjectName("Login_3")
        self.Login_7 = QtWidgets.QLabel(self.centralwidget)
        self.Login_7.setEnabled(False)
        self.Login_7.setGeometry(QtCore.QRect(119, 181, 111, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Login_7.sizePolicy().hasHeightForWidth())
        self.Login_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Login_7.setFont(font)
        self.Login_7.setStyleSheet("color: rgb(166, 166, 166);\n"
"background-color: rgb(26,26,26);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;")
        self.Login_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Login_7.setObjectName("Login_7")
        self.Login_6 = QtWidgets.QLabel(self.centralwidget)
        self.Login_6.setEnabled(False)
        self.Login_6.setGeometry(QtCore.QRect(19, 150, 211, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Login_6.sizePolicy().hasHeightForWidth())
        self.Login_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Login_6.setFont(font)
        self.Login_6.setStyleSheet("color: rgb(166, 166, 166);\n"
"background-color: rgb(26,26,26);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;")
        self.Login_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Login_6.setObjectName("Login_6")
        self.Login_8 = QtWidgets.QLabel(self.centralwidget)
        self.Login_8.setEnabled(False)
        self.Login_8.setGeometry(QtCore.QRect(79, 282, 151, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Login_8.sizePolicy().hasHeightForWidth())
        self.Login_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Login_8.setFont(font)
        self.Login_8.setStyleSheet("color: rgb(166, 166, 166);\n"
"background-color: rgb(26,26,26);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;")
        self.Login_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Login_8.setObjectName("Login_8")
        self.Login_5 = QtWidgets.QLabel(self.centralwidget)
        self.Login_5.setEnabled(False)
        self.Login_5.setGeometry(QtCore.QRect(150, 120, 80, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Login_5.sizePolicy().hasHeightForWidth())
        self.Login_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Login_5.setFont(font)
        self.Login_5.setStyleSheet("color: rgb(166, 166, 166);\n"
"background-color: rgb(26,26,26);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;")
        self.Login_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Login_5.setObjectName("Login_5")
        self.author_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.author_lineEdit.setGeometry(QtCore.QRect(240, 60, 361, 22))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.author_lineEdit.setFont(font)
        self.author_lineEdit.setStyleSheet("color: rgb(166, 166, 166);\n"
"background-color: rgb(41,41,41);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;")
        self.author_lineEdit.setObjectName("author_lineEdit")
        self.genre_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.genre_lineEdit.setGeometry(QtCore.QRect(240, 120, 361, 22))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.genre_lineEdit.setFont(font)
        self.genre_lineEdit.setStyleSheet("color: rgb(166, 166, 166);\n"
"background-color: rgb(41,41,41);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;")
        self.genre_lineEdit.setObjectName("genre_lineEdit")
        self.book_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.book_lineEdit.setGeometry(QtCore.QRect(240, 90, 361, 22))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.book_lineEdit.setFont(font)
        self.book_lineEdit.setStyleSheet("color: rgb(166, 166, 166);\n"
"background-color: rgb(41,41,41);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;")
        self.book_lineEdit.setText("")
        self.book_lineEdit.setObjectName("book_lineEdit")
        self.year_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.year_lineEdit.setGeometry(QtCore.QRect(240, 150, 361, 22))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.year_lineEdit.setFont(font)
        self.year_lineEdit.setStyleSheet("color: rgb(166, 166, 166);\n"
"background-color: rgb(41,41,41);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;")
        self.year_lineEdit.setText("")
        self.year_lineEdit.setObjectName("year_lineEdit")
        self.rating_SpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.rating_SpinBox.setGeometry(QtCore.QRect(240, 380, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rating_SpinBox.setFont(font)
        self.rating_SpinBox.setStyleSheet("color: rgb(166, 166, 166);\n"
"background-color: rgb(41,41,41);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;")
        self.rating_SpinBox.setDecimals(2)
        self.rating_SpinBox.setMaximum(10.0)
        self.rating_SpinBox.setSingleStep(0.5)
        self.rating_SpinBox.setObjectName("rating_SpinBox")
        self.label_header = QtWidgets.QLabel(self.centralwidget)
        self.label_header.setEnabled(False)
        self.label_header.setGeometry(QtCore.QRect(70, 19, 531, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_header.sizePolicy().hasHeightForWidth())
        self.label_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_header.setFont(font)
        self.label_header.setStyleSheet("color: rgb(70, 70, 70);\n"
"background-color: rgb(26,26,26);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;")
        self.label_header.setAlignment(QtCore.Qt.AlignCenter)
        self.label_header.setObjectName("label_header")
        self.add_book_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.add_book_pushButton.setGeometry(QtCore.QRect(190, 420, 298, 54))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.add_book_pushButton.setFont(font)
        self.add_book_pushButton.setStyleSheet("QPushButton {\n"
"color: rgb(160, 160, 160);\n"
"background-color: rgb(41, 41,41);\n"
"text-align: left;\n"
"border: 2px solid rgb(30, 30, 30);\n"
"margin: 0px;\n"
"padding: 0px;\n"
"text-align: center;\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"color: rgb(160, 160, 160);\n"
"background-color: rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(30,30,30);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/resources/icons/add_task_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_book_pushButton.setIcon(icon1)
        self.add_book_pushButton.setIconSize(QtCore.QSize(50, 50))
        self.add_book_pushButton.setObjectName("add_book_pushButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(240, 180, 415, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fiction_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.fiction_radioButton.setFont(font)
        self.fiction_radioButton.setStyleSheet("color: rgb(166, 166, 166);\n"
"background-color: rgb(26,26,26);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;")
        self.fiction_radioButton.setObjectName("fiction_radioButton")
        self.verticalLayout.addWidget(self.fiction_radioButton)
        self.technical_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.technical_radioButton.setFont(font)
        self.technical_radioButton.setStyleSheet("color: rgb(166, 166, 166);\n"
"background-color: rgb(26,26,26);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;")
        self.technical_radioButton.setObjectName("technical_radioButton")
        self.verticalLayout.addWidget(self.technical_radioButton)
        self.self_help_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.self_help_radioButton.setFont(font)
        self.self_help_radioButton.setStyleSheet("color: rgb(166, 166, 166);\n"
"background-color: rgb(26,26,26);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;")
        self.self_help_radioButton.setObjectName("self_help_radioButton")
        self.verticalLayout.addWidget(self.self_help_radioButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(240, 280, 181, 91))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.yes_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.yes_radioButton.setFont(font)
        self.yes_radioButton.setStyleSheet("color: rgb(166, 166, 166);\n"
"background-color: rgb(26,26,26);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;")
        self.yes_radioButton.setObjectName("yes_radioButton")
        self.verticalLayout_2.addWidget(self.yes_radioButton)
        self.no_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.no_radioButton.setFont(font)
        self.no_radioButton.setStyleSheet("color: rgb(166, 166, 166);\n"
"background-color: rgb(26,26,26);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;")
        self.no_radioButton.setObjectName("no_radioButton")
        self.verticalLayout_2.addWidget(self.no_radioButton)
        self.during_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.during_radioButton.setFont(font)
        self.during_radioButton.setStyleSheet("color: rgb(166, 166, 166);\n"
"background-color: rgb(26,26,26);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;")
        self.during_radioButton.setObjectName("during_radioButton")
        self.verticalLayout_2.addWidget(self.during_radioButton)
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(620, 460, 31, 28))
        self.exit_button.setStyleSheet("QPushButton {\n"
"color: rgb(160, 160, 160);\n"
"background-color: rgb(41, 41,41);\n"
"text-align: left;\n"
"border: 2px solid rgb(30, 30, 30);\n"
"margin: 0px;\n"
"padding: 0px;\n"
"text-align: center;\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"color: rgb(160, 160, 160);\n"
"background-color: rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(30,30,30);\n"
"}")
        self.exit_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/resources/icons/login_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_button.setIcon(icon2)
        self.exit_button.setIconSize(QtCore.QSize(40, 40))
        self.exit_button.setObjectName("exit_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "addBook"))
        self.Login_9.setText(_translate("MainWindow", "Рейтинг:"))
        self.Login_4.setText(_translate("MainWindow", "Название книги:"))
        self.Login_3.setText(_translate("MainWindow", "Автор:"))
        self.Login_7.setText(_translate("MainWindow", "Раздел:"))
        self.Login_6.setText(_translate("MainWindow", "Год написания:"))
        self.Login_8.setText(_translate("MainWindow", "Прочитано:"))
        self.Login_5.setText(_translate("MainWindow", "Жанр:"))
        self.label_header.setText(_translate("MainWindow", "Макет добавления книги"))
        self.add_book_pushButton.setText(_translate("MainWindow", "Добавить кингу"))
        self.fiction_radioButton.setText(_translate("MainWindow", "Художественная литература"))
        self.technical_radioButton.setText(_translate("MainWindow", "Техническая литература"))
        self.self_help_radioButton.setText(_translate("MainWindow", "Литература по саморазвитию"))
        self.yes_radioButton.setText(_translate("MainWindow", "Да"))
        self.no_radioButton.setText(_translate("MainWindow", "Нет"))
        self.during_radioButton.setText(_translate("MainWindow", "В процессе"))
import icons_rc
