# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/delete.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(645, 577)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/resources/icons/delete_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget\n"
"{\n"
"background-color: rgb(26,26,26);\n"
"}\n"
"QTableCornerButton::section\n"
"{\n"
"background-color: rgb(46, 46, 46); \n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"\n"
"  border: none;\n"
"  background-color: rgb(46, 46, 46);\n"
"  width: 15px;\n"
"  margin: 21px 0 21px 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"  border: 2px solid rgb(61, 61, 61);\n"
"  background-color: rgb(20, 20, 20);\n"
"  min-height: 25px;\n"
"\n"
"}\n"
"\n"
" QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"  background-color: rgb(20, 20, 20);\n"
"    height: 20px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(20, 20, 20);\n"
"    height: 20px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"  QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"      background: none;\n"
"  }\n"
"\n"
"QScrollBar::up-arrow:vertical\n"
"{\n"
"  image: url(:/BarIcon/Icons/uparrow.png);\n"
"}\n"
"\n"
"QScrollBar::down-arrow:vertical\n"
"{\n"
"  image: url(:/BarIcon/Icons/downarrow.png);\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"  border: none;\n"
"  background-color: rgb(46, 46, 46);\n"
"    height: 15px;\n"
"    margin: 0px 21px 0 21px;\n"
" }\n"
"\n"
" QScrollBar::handle:horizontal {\n"
"    border: 2px solid rgb(61, 61, 61);\n"
"    background-color: rgb(20, 20, 20);\n"
"    min-width: 25px;\n"
" }\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"  background-color: rgb(20, 20, 20);\n"
"    height: 20px;\n"
"    width: 20px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
" }\n"
"\n"
" QScrollBar::sub-line:horizontal {\n"
"  border: none;\n"
"    background-color: rgb(20, 20, 20);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
" }\n"
"\n"
"\n"
"\n"
"\n"
" QScrollBar:left-arrow:horizontal\n"
"{\n"
"  image: url(:/BarIcon/Icons/leftarrow.png);\n"
"}\n"
"\n"
"QScrollBar::right-arrow:horizontal \n"
"{\n"
"  image: url(:/BarIcon/Icons/rightarrow.png);\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"     background: none;\n"
"}")
        MainWindow.setIconSize(QtCore.QSize(40, 40))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_header = QtWidgets.QLabel(self.centralwidget)
        self.label_header.setEnabled(False)
        self.label_header.setGeometry(QtCore.QRect(-40, 20, 731, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_header.sizePolicy().hasHeightForWidth())
        self.label_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_header.setFont(font)
        self.label_header.setStyleSheet("color: rgb(70, 70, 70);\n"
"background-color: rgb(26,26,26);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;")
        self.label_header.setAlignment(QtCore.Qt.AlignCenter)
        self.label_header.setObjectName("label_header")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 60, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(166, 166, 166);\n"
"background-color: rgb(26,26,26);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.id_book = QtWidgets.QSpinBox(self.centralwidget)
        self.id_book.setGeometry(QtCore.QRect(380, 60, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.id_book.setFont(font)
        self.id_book.setStyleSheet("color: rgb(166, 166, 166);\n"
"background-color: rgb(41,41,41);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;")
        self.id_book.setMinimum(1)
        self.id_book.setMaximum(999999999)
        self.id_book.setObjectName("id_book")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 140, 601, 341))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bookTable = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bookTable.setFont(font)
        self.bookTable.setStyleSheet("QTableView\n"
"{\n"
"border: 4px solid rgb(30, 30, 30);\n"
"margin: 0px;\n"
"padding: 0px;\n"
"}\n"
"\n"
"QHeaderView\n"
" {\n"
"    color: rgb(165, 165, 165);\n"
"    background-color: rgb(46, 46, 46);\n"
"    text-align: center;\n"
"    border: none;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QHeaderView::section\n"
" {\n"
"    color: rgb(165, 165, 165);\n"
"    background-color: rgb(46, 46, 46);\n"
"    text-align: center;\n"
"    border: none;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QHeaderView::section:hover\n"
" {\n"
"    color: rgb(165, 165, 165);\n"
"    background-color: rgb(70, 70, 70);\n"
"    text-align: center;\n"
"    border: none;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QHeaderView::section:pressed\n"
" {\n"
"    color: rgb(165, 165, 165);\n"
"    background-color: rgb(30, 30, 30);\n"
"    text-align: center;\n"
"    border: none;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"\n"
"QTableView::item \n"
"{   \n"
"    color: rgb(166, 166, 166);        \n"
"}\n"
"\n"
"        \n"
"QTableView::item:selected\n"
"{   \n"
"    background-color: rgb(61, 61, 61);     \n"
"}\n"
"")
        self.bookTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.bookTable.setAutoScroll(False)
        self.bookTable.setAutoScrollMargin(10)
        self.bookTable.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.bookTable.setObjectName("bookTable")
        self.bookTable.setColumnCount(0)
        self.bookTable.setRowCount(0)
        self.verticalLayout.addWidget(self.bookTable)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 110, 601, 26))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.search_label.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_label.sizePolicy().hasHeightForWidth())
        self.search_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.search_label.setFont(font)
        self.search_label.setStyleSheet("color: rgb(166, 166, 166);\n"
"background-color: rgb(41,41,41);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;")
        self.search_label.setScaledContents(False)
        self.search_label.setObjectName("search_label")
        self.horizontalLayout.addWidget(self.search_label)
        self.search_line = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_line.sizePolicy().hasHeightForWidth())
        self.search_line.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.search_line.setFont(font)
        self.search_line.setStyleSheet("color: rgb(166, 166, 166);\n"
"background-color: rgb(41,41,41);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;")
        self.search_line.setText("")
        self.search_line.setObjectName("search_line")
        self.horizontalLayout.addWidget(self.search_line)
        self.delete_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_button.setGeometry(QtCore.QRect(240, 490, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.delete_button.setFont(font)
        self.delete_button.setStyleSheet("QPushButton {\n"
"color: rgb(160, 160, 160);\n"
"background-color: rgb(41, 41,41);\n"
"text-align: left;\n"
"border: 2px solid rgb(30, 30, 30);\n"
"margin: 0px;\n"
"padding: 0px;\n"
"text-align: center;\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"color: rgb(160, 160, 160);\n"
"background-color: rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(30,30,30);\n"
"}")
        self.delete_button.setIcon(icon)
        self.delete_button.setObjectName("delete_button")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(590, 530, 31, 28))
        self.exit_button.setStyleSheet("QPushButton {\n"
"color: rgb(160, 160, 160);\n"
"background-color: rgb(41, 41,41);\n"
"text-align: left;\n"
"border: 2px solid rgb(30, 30, 30);\n"
"margin: 0px;\n"
"padding: 0px;\n"
"text-align: center;\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"color: rgb(160, 160, 160);\n"
"background-color: rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(30,30,30);\n"
"}")
        self.exit_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/resources/icons/login_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_button.setIcon(icon1)
        self.exit_button.setIconSize(QtCore.QSize(40, 40))
        self.exit_button.setObjectName("exit_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DeleteBook"))
        self.label_header.setText(_translate("MainWindow", "Макет удаления книги"))
        self.label.setText(_translate("MainWindow", "Введите id книги: "))
        self.search_label.setText(_translate("MainWindow", "Search book:"))
        self.delete_button.setText(_translate("MainWindow", "Удалить"))
import icons_rc
