# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/MyLib.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1132, 589)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1132, 589))
        MainWindow.setMaximumSize(QtCore.QSize(1132, 589))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/resources/icons/library_books_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget\n"
"{\n"
"background-color: rgb(26,26,26);\n"
"}\n"
"QTableCornerButton::section\n"
"{\n"
"background-color: rgb(46, 46, 46); \n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"\n"
"  border: none;\n"
"  background-color: rgb(46, 46, 46);\n"
"  width: 15px;\n"
"  margin: 21px 0 21px 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"  border: 2px solid rgb(61, 61, 61);\n"
"  background-color: rgb(20, 20, 20);\n"
"  min-height: 25px;\n"
"\n"
"}\n"
"\n"
" QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"  background-color: rgb(20, 20, 20);\n"
"    height: 20px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(20, 20, 20);\n"
"    height: 20px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"  QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"      background: none;\n"
"  }\n"
"\n"
"QScrollBar::up-arrow:vertical\n"
"{\n"
"  image: url(:/BarIcon/Icons/uparrow.png);\n"
"}\n"
"\n"
"QScrollBar::down-arrow:vertical\n"
"{\n"
"  image: url(:/BarIcon/Icons/downarrow.png);\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"  border: none;\n"
"  background-color: rgb(46, 46, 46);\n"
"    height: 15px;\n"
"    margin: 0px 21px 0 21px;\n"
" }\n"
"\n"
" QScrollBar::handle:horizontal {\n"
"    border: 2px solid rgb(61, 61, 61);\n"
"    background-color: rgb(20, 20, 20);\n"
"    min-width: 25px;\n"
" }\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"  background-color: rgb(20, 20, 20);\n"
"    height: 20px;\n"
"    width: 20px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
" }\n"
"\n"
" QScrollBar::sub-line:horizontal {\n"
"  border: none;\n"
"    background-color: rgb(20, 20, 20);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
" }\n"
"\n"
"\n"
"\n"
"\n"
" QScrollBar:left-arrow:horizontal\n"
"{\n"
"  image: url(:/BarIcon/Icons/leftarrow.png);\n"
"}\n"
"\n"
"QScrollBar::right-arrow:horizontal \n"
"{\n"
"  image: url(:/BarIcon/Icons/rightarrow.png);\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"     background: none;\n"
"}")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -1090, 263, 1433))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("background-color: rgb(41,41,41);\n"
"border: 2px solid black;\n"
"border-color: rgb(61, 61, 61);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 4, 251, 171))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Login_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Login_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Login_2.sizePolicy().hasHeightForWidth())
        self.Login_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Login_2.setFont(font)
        self.Login_2.setStyleSheet("color: rgb(166, 166, 166);\n"
"background-color: rgb(41,41,41);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;")
        self.Login_2.setObjectName("Login_2")
        self.verticalLayout_2.addWidget(self.Login_2)
        self.new_book = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_book.sizePolicy().hasHeightForWidth())
        self.new_book.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.new_book.setFont(font)
        self.new_book.setAutoFillBackground(False)
        self.new_book.setStyleSheet("QPushButton {\n"
"color: rgb(160, 160, 160);\n"
"background-color: rgb(41,41,41);\n"
"text-align: left;\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;\n"
"}\n"
"QPushButton:hover {\n"
"color: rgb(160, 160, 160);\n"
"background-color: rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(30,30,30);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/resources/icons/book_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.new_book.setIcon(icon1)
        self.new_book.setIconSize(QtCore.QSize(50, 50))
        self.new_book.setObjectName("new_book")
        self.verticalLayout_2.addWidget(self.new_book)
        self.Delete_book = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Delete_book.sizePolicy().hasHeightForWidth())
        self.Delete_book.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Delete_book.setFont(font)
        self.Delete_book.setStyleSheet("QPushButton {\n"
"color: rgb(160, 160, 160);\n"
"background-color: rgb(41,41,41);\n"
"text-align: left;\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;\n"
"}\n"
"QPushButton:hover {\n"
"color: rgb(160, 160, 160);\n"
"background-color: rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(30,30,30);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/resources/icons/delete_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Delete_book.setIcon(icon2)
        self.Delete_book.setIconSize(QtCore.QSize(50, 50))
        self.Delete_book.setObjectName("Delete_book")
        self.verticalLayout_2.addWidget(self.Delete_book)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(280, 40, 811, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bookTable = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bookTable.setFont(font)
        self.bookTable.setStyleSheet("QTableView\n"
"{\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;\n"
"}\n"
"\n"
"QHeaderView\n"
" {\n"
"    color: rgb(165, 165, 165);\n"
"    background-color: rgb(46, 46, 46);\n"
"    text-align: center;\n"
"    border: none;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QHeaderView::section\n"
" {\n"
"    color: rgb(165, 165, 165);\n"
"    background-color: rgb(46, 46, 46);\n"
"    text-align: center;\n"
"    border: none;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QHeaderView::section:hover\n"
" {\n"
"    color: rgb(165, 165, 165);\n"
"    background-color: rgb(70, 70, 70);\n"
"    text-align: center;\n"
"    border: none;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QHeaderView::section:pressed\n"
" {\n"
"    color: rgb(165, 165, 165);\n"
"    background-color: rgb(30, 30, 30);\n"
"    text-align: center;\n"
"    border: none;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"\n"
"QTableView::item \n"
"{   \n"
"    color: rgb(166, 166, 166);        \n"
"}\n"
"\n"
"        \n"
"QTableView::item:selected\n"
"{   \n"
"    background-color: rgb(61, 61, 61);     \n"
"}\n"
"")
        self.bookTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.bookTable.setAutoScroll(False)
        self.bookTable.setAutoScrollMargin(10)
        self.bookTable.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.bookTable.setObjectName("bookTable")
        self.bookTable.setColumnCount(0)
        self.bookTable.setRowCount(0)
        self.verticalLayout.addWidget(self.bookTable)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(280, 10, 811, 26))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.search_label.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_label.sizePolicy().hasHeightForWidth())
        self.search_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.search_label.setFont(font)
        self.search_label.setStyleSheet("color: rgb(166, 166, 166);\n"
"background-color: rgb(41,41,41);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;")
        self.search_label.setScaledContents(False)
        self.search_label.setObjectName("search_label")
        self.horizontalLayout.addWidget(self.search_label)
        self.search_line = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_line.sizePolicy().hasHeightForWidth())
        self.search_line.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.search_line.setFont(font)
        self.search_line.setStyleSheet("color: rgb(166, 166, 166);\n"
"background-color: rgb(41,41,41);\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;")
        self.search_line.setText("")
        self.search_line.setObjectName("search_line")
        self.horizontalLayout.addWidget(self.search_line)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 190, 251, 151))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Select_book = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Select_book.sizePolicy().hasHeightForWidth())
        self.Select_book.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Select_book.setFont(font)
        self.Select_book.setStyleSheet("QPushButton {\n"
"color: rgb(160, 160, 160);\n"
"background-color: rgb(41,41,41);\n"
"text-align: left;\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;\n"
"}\n"
"QPushButton:hover {\n"
"color: rgb(160, 160, 160);\n"
"background-color: rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(30,30,30);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/resources/icons/menu_book_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Select_book.setIcon(icon3)
        self.Select_book.setIconSize(QtCore.QSize(50, 50))
        self.Select_book.setObjectName("Select_book")
        self.verticalLayout_3.addWidget(self.Select_book)
        self.load_book = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_book.sizePolicy().hasHeightForWidth())
        self.load_book.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.load_book.setFont(font)
        self.load_book.setStyleSheet("QPushButton {\n"
"color: rgb(160, 160, 160);\n"
"background-color: rgb(41,41,41);\n"
"text-align: left;\n"
"border: none;\n"
"margin: 0px;\n"
"padding: 0px;\n"
"}\n"
"QPushButton:hover {\n"
"color: rgb(160, 160, 160);\n"
"background-color: rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(30,30,30);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/resources/icons/ios_share_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.load_book.setIcon(icon4)
        self.load_book.setIconSize(QtCore.QSize(50, 50))
        self.load_book.setObjectName("load_book")
        self.verticalLayout_3.addWidget(self.load_book)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 173, 251, 16))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MyLib"))
        self.Login_2.setText(_translate("MainWindow", "Actions:"))
        self.new_book.setText(_translate("MainWindow", "Add book to table"))
        self.Delete_book.setText(_translate("MainWindow", "Delete book"))
        self.search_label.setText(_translate("MainWindow", "Search book:"))
        self.Select_book.setText(_translate("MainWindow", "Library"))
        self.load_book.setText(_translate("MainWindow", "load book"))
import icons_rc
import icons_rc
